#!/usr/bin/env python
# encoding: utf-8

import os
import shutil
import subprocess

APPNAME = 'tun'
VERSION = '0.1-NO-KODO'

top = '.'
out = 'build'

def options(opt):
    opt.load('compiler_cxx')

def configure(conf):
    conf.load('compiler_cxx')

def build(bld):
#    bld.cxx_flags = ['-O3', '-ggdb', '-g', '-std=c++11', '-Wall', '-Wextra', '-pedantic', '-Werror', '-pthread','-Wno-unused-local-typedefs', '-ftree-vectorizer-verbose=1']
    bld.cxx_flags = ['-O3', '-ggdb', '-g', '-std=c++11', '-Wall', '-Wextra', '-pedantic', '-Werror', '-pthread','-Wno-unused-local-typedefs']

    quit = bld.stlib(
        features = 'cxx',
        source = ['src/quit.cpp'],
        target = 'quit',
        includes = 'src',
        cxxflags = bld.cxx_flags)

    bld.recurse('apps')
    bld.recurse('test')
