#!/usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.program(features = 'cxx',
                source = ['general.cpp', 'src/pkt_buffers.cpp', 'src/delay_pkt.cpp', 'src/xor_redundancy.cpp', 'src/drop_pkt.cpp', 'src/file_layer.cpp', 'src/stack_args.cpp', 'src/connector.cpp', 'src/filter.cpp', 'src/generators.cpp'],
                target = 'general',
                includes = ['../src', 'src'],
                cxxflags = bld.cxx_flags,
                lib = ['pthread'])

#    profiling_flags = ['-fprofile-arcs', '-ftest-coverage', '--coverage', '-O0']
#    bld.program(features = 'cxx',
#                source = ['general.cpp', 'src/pkt_buffers.cpp', 'src/delay_pkt.cpp', 'src/xor_redundancy.cpp', 'src/kodo.cpp', 'src/drop_pkt.cpp', 'src/file_layer.cpp', 'src/stack_args.cpp', 'src/connector.cpp', 'src/filter.cpp', 'src/generators.cpp'],
#                target = 'general_profiling',
#                includes = ['../src', 'src'],
#                cxxflags = profiling_flags,
#                linkflags = profiling_flags,
#                use = bld.kodo_use,
#                lib = ['pthread'])
