#!/usr/bin/env python
# encoding: utf-8

def build(bld):
    inlude_dirs = ['../../src']

#    pc_kodo = bld.program(
#        features = 'cxx',
#        source = ['pc_kodo.cpp'],
#        target = 'pc_kodo',
#        includes = inlude_dirs,
#        cxxflags = bld.cxx_flags,
#        use = bld.kodo_use,
#        lib = ['pthread'])

#    pc_recoder = bld.program(
#        features = 'cxx',
#        source = ['pc_recoder.cpp'],
#        target = 'pc_recoder',
#        includes = inlude_dirs,
#        cxxflags = bld.cxx_flags,
#        use = bld.kodo_use,
#        lib = ['pthread'])

    pc_forwarder = bld.program(
        features = 'cxx',
        source = ['pc_forwarder.cpp'],
        target = 'pc_forwarder',
        includes = inlude_dirs,
        cxxflags = bld.cxx_flags,
        use = ['quit'],
        lib = ['pthread'])

#    pc_kodo_xor = bld.program(
#        features = 'cxx',
#        source = ['pc_kodo_xor.cpp'],
#        target = 'pc_kodo_xor',
#        includes = inlude_dirs,
#        cxxflags = bld.cxx_flags,
#        use = bld.kodo_use,
#        lib = ['pthread'])

    pc_xor = bld.program(
        features = 'cxx',
        source = ['pc_xor.cpp'],
        target = 'pc_xor',
        includes = inlude_dirs,
        cxxflags = bld.cxx_flags,
        use = ['quit'],
        lib = ['pthread'])

    pc_xora = bld.program(
        features = 'cxx',
        source = ['pc_xora.cpp'],
        target = 'pc_xora',
        includes = inlude_dirs,
        cxxflags = bld.cxx_flags,
        use = ['quit'],
        lib = ['pthread'])
